# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CTX_Polar_CRS_Toolbox
                                 A QGIS plugin
 This plug-ins edits custom CTX Polar CRS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-07-19
        copyright            : (C) 2025 by Quentin Betton
        email                : quentin.btn45@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Quentin Betton'
__date__ = '2025-07-19'
__copyright__ = '(C) 2025 by Quentin Betton'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CTX_Polar_CRS_Toolbox class from file CTX_Polar_CRS_Toolbox.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ctx_polar _crs_toolbox import CTX_Polar_CRS_ToolboxPlugin
    return CTX_Polar_CRS_ToolboxPlugin()
